### **Posttest 7 KB**
### Fayza Virdana Addiza
### 2009106004

In [49]:
import tensorflow as tf

# Membuat sebuah tensor dengan shape(5,5) dengan nilai random yang disimpan dalam variable **random_tensor**

In [50]:
random_tensor = tf.random.normal([5,5], mean=0, stddev=1, seed=1)
random_tensor

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[-0.32386488,  0.99133694,  0.14024267,  1.2573972 ,  0.09992335],
       [ 0.18983224, -0.28711194, -1.7413595 ,  1.8718754 , -2.0104504 ],
       [-1.4673029 , -1.2721989 , -0.7803738 ,  0.94073033, -0.06164822],
       [-2.0842526 ,  0.61423135, -1.451092  , -0.88693523, -0.96740866],
       [ 0.94831836, -0.6974499 ,  0.5391437 , -0.52970064, -2.0105364 ]],
      dtype=float32)>

# Membuat sebuah tensor dengan shape(5,5) dari sebuah list dengan nilai bilangan prima dalam variable **prime_tensor**

In [51]:
prime_tensor= [[2, 3, 5, 7, 11], [13, 17, 19, 23, 29], [23, 19, 2, 7, 17], [17, 7, 37, 11, 3],[31, 11, 2, 5, 37]]

tf.convert_to_tensor(prime_tensor, dtype=tf.int64)

<tf.Tensor: shape=(5, 5), dtype=int64, numpy=
array([[ 2,  3,  5,  7, 11],
       [13, 17, 19, 23, 29],
       [23, 19,  2,  7, 17],
       [17,  7, 37, 11,  3],
       [31, 11,  2,  5, 37]], dtype=int64)>

# Tampilkan dimensi dari kedua variable tersebut
 - ## Menampilkan dimensi dari variabel random_tensor

In [52]:
print("Dimensi kulit pertama random_tensor :\n", random_tensor[0:1], "\n")
print("Dimensi kulit kedua random_tensor :\n", random_tensor[1:2], "\n")
print("Dimensi kulit ketiga random_tensor :\n", random_tensor[2:3], "\n")
print("Dimensi kulit keempat random_tensor :\n", random_tensor[3:4], "\n")
print("Dimensi kulit kelima random_tensor :\n", random_tensor[4:5])


Dimensi kulit pertama random_tensor :
 tf.Tensor([[-0.32386488  0.99133694  0.14024267  1.2573972   0.09992335]], shape=(1, 5), dtype=float32) 

Dimensi kulit kedua random_tensor :
 tf.Tensor([[ 0.18983224 -0.28711194 -1.7413595   1.8718754  -2.0104504 ]], shape=(1, 5), dtype=float32) 

Dimensi kulit ketiga random_tensor :
 tf.Tensor([[-1.4673029  -1.2721989  -0.7803738   0.94073033 -0.06164822]], shape=(1, 5), dtype=float32) 

Dimensi kulit keempat random_tensor :
 tf.Tensor([[-2.0842526   0.61423135 -1.451092   -0.88693523 -0.96740866]], shape=(1, 5), dtype=float32) 

Dimensi kulit kelima random_tensor :
 tf.Tensor([[ 0.94831836 -0.6974499   0.5391437  -0.52970064 -2.0105364 ]], shape=(1, 5), dtype=float32)


- ## Menampilkan satu element dari variabel random_tensor

In [53]:
print("Element random_tensor baris ke-1, kolom ke-2 :", random_tensor[0,1], "\n")
print("Element random_tensor baris ke-5, kolom ke-3 :", random_tensor[4,2], "\n")
print("Element random_tensor baris ke-3, kolom ke-4 :", random_tensor[2,3], "\n")

Element random_tensor baris ke-1, kolom ke-2 : tf.Tensor(0.99133694, shape=(), dtype=float32) 

Element random_tensor baris ke-5, kolom ke-3 : tf.Tensor(0.5391437, shape=(), dtype=float32) 

Element random_tensor baris ke-3, kolom ke-4 : tf.Tensor(0.94073033, shape=(), dtype=float32) 



- ## Menampilkan dimensi dari variabel prime_tensor

In [54]:
print("Dimensi kulit pertama prime_tensor :\n", prime_tensor[0:1], "\n")
print("Dimensi kulit kedua prime_tensor :\n", prime_tensor[1:2], "\n")
print("Dimensi kulit ketiga prime_tensor :\n", prime_tensor[2:3], "\n")
print("Dimensi kulit keempat prime_tensor :\n", prime_tensor[3:4], "\n")
print("Dimensi kulit kelima prime_tensor :\n", prime_tensor[4:5])

Dimensi kulit pertama prime_tensor :
 [[2, 3, 5, 7, 11]] 

Dimensi kulit kedua prime_tensor :
 [[13, 17, 19, 23, 29]] 

Dimensi kulit ketiga prime_tensor :
 [[23, 19, 2, 7, 17]] 

Dimensi kulit keempat prime_tensor :
 [[17, 7, 37, 11, 3]] 

Dimensi kulit kelima prime_tensor :
 [[31, 11, 2, 5, 37]]


# Tampilkan hasil dari perhitungan aritmetika

In [55]:
# pertambahan
tf.add(random_tensor, prime_tensor)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ 1.6761351,  3.9913368,  5.1402426,  8.257397 , 11.099923 ],
       [13.189833 , 16.712889 , 17.25864  , 24.871876 , 26.98955  ],
       [21.532698 , 17.7278   ,  1.2196262,  7.94073  , 16.938353 ],
       [14.915748 ,  7.614231 , 35.54891  , 10.113065 ,  2.0325913],
       [31.948318 , 10.30255  ,  2.5391436,  4.4702992, 34.989464 ]],
      dtype=float32)>

In [56]:
# pengurangan
tf.subtract(random_tensor, prime_tensor)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ -2.323865 ,  -2.0086632,  -4.8597574,  -5.742603 , -10.900077 ],
       [-12.810167 , -17.287111 , -20.74136  , -21.128124 , -31.01045  ],
       [-24.467302 , -20.2722   ,  -2.7803738,  -6.05927  , -17.061647 ],
       [-19.084253 ,  -6.385769 , -38.45109  , -11.886935 ,  -3.9674087],
       [-30.051682 , -11.69745  ,  -1.4608563,  -5.5297008, -39.010536 ]],
      dtype=float32)>

In [59]:
# perkalian
tf.multiply(random_tensor, prime_tensor)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ -0.64772975,   2.974011  ,   0.70121336,   8.801781  ,
          1.0991569 ],
       [  2.4678192 ,  -4.880903  , -33.08583   ,  43.053135  ,
        -58.303062  ],
       [-33.747967  , -24.17178   ,  -1.5607476 ,   6.5851126 ,
         -1.0480198 ],
       [-35.432293  ,   4.2996197 , -53.690403  ,  -9.756288  ,
         -2.902226  ],
       [ 29.39787   ,  -7.6719494 ,   1.0782874 ,  -2.6485033 ,
        -74.38985   ]], dtype=float32)>

In [58]:
# pembagian
tf.divide(random_tensor, prime_tensor)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[-0.16193244,  0.33044565,  0.02804853,  0.17962816,  0.00908394],
       [ 0.01460248, -0.01688894, -0.0916505 ,  0.08138589, -0.06932587],
       [-0.06379578, -0.06695784, -0.3901869 ,  0.13439004, -0.00362637],
       [-0.1226031 ,  0.08774734, -0.0392187 , -0.08063047, -0.32246956],
       [ 0.03059091, -0.06340454,  0.26957184, -0.10594013, -0.05433882]],
      dtype=float32)>

In [60]:
# perpangkatan
tf.pow(random_tensor, prime_tensor)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ 1.0488846e-01,  9.7423530e-01,  5.4250133e-05,  4.9694390e+00,
         9.9160073e-12],
       [ 4.1572837e-10, -6.1216887e-10, -3.7746809e+04,  1.8296565e+06,
        -6.2446387e+08],
       [-6.7601289e+03, -9.6949463e+01,  6.0898328e-01,  6.5201265e-01,
        -2.6831788e-21],
       [-2.6433578e+05,  3.2985557e-02, -9.6097731e+05, -2.6718432e-01,
        -9.0537792e-01],
       [ 1.9300961e-01, -1.8995177e-02,  2.9067591e-01, -4.1701578e-02,
        -1.6693294e+11]], dtype=float32)>

# Tampilkan nilai maksimal dan minimal dari variable random_tensor

In [61]:
# posisi nilai maksimal berdasarkan kolom
tf.argmax(random_tensor, axis=0)

<tf.Tensor: shape=(5,), dtype=int64, numpy=array([4, 0, 4, 1, 0], dtype=int64)>

In [62]:
# posisi nilai minimal berdasarkan baris
tf.argmin(random_tensor, axis=1)

<tf.Tensor: shape=(5,), dtype=int64, numpy=array([0, 4, 0, 0, 4], dtype=int64)>

# Tampilkan hasil dari penggabungan variable random_tensor dengan prime_tensor (concatenation)

In [63]:
gabung_tensor = tf.concat([random_tensor, prime_tensor], axis=0)
print(gabung_tensor.shape)
print(gabung_tensor)

(10, 5)
tf.Tensor(
[[-0.32386488  0.99133694  0.14024267  1.2573972   0.09992335]
 [ 0.18983224 -0.28711194 -1.7413595   1.8718754  -2.0104504 ]
 [-1.4673029  -1.2721989  -0.7803738   0.94073033 -0.06164822]
 [-2.0842526   0.61423135 -1.451092   -0.88693523 -0.96740866]
 [ 0.94831836 -0.6974499   0.5391437  -0.52970064 -2.0105364 ]
 [ 2.          3.          5.          7.         11.        ]
 [13.         17.         19.         23.         29.        ]
 [23.         19.          2.          7.         17.        ]
 [17.          7.         37.         11.          3.        ]
 [31.         11.          2.          5.         37.        ]], shape=(10, 5), dtype=float32)


# Tampilkan hasil sorting dari kedua variable di atas. (descending)

In [64]:
tf.sort(random_tensor, direction='DESCENDING')

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ 1.2573972 ,  0.99133694,  0.14024267,  0.09992335, -0.32386488],
       [ 1.8718754 ,  0.18983224, -0.28711194, -1.7413595 , -2.0104504 ],
       [ 0.94073033, -0.06164822, -0.7803738 , -1.2721989 , -1.4673029 ],
       [ 0.61423135, -0.88693523, -0.96740866, -1.451092  , -2.0842526 ],
       [ 0.94831836,  0.5391437 , -0.52970064, -0.6974499 , -2.0105364 ]],
      dtype=float32)>

In [65]:
tf.sort(prime_tensor, direction='DESCENDING')

<tf.Tensor: shape=(5, 5), dtype=int32, numpy=
array([[11,  7,  5,  3,  2],
       [29, 23, 19, 17, 13],
       [23, 19, 17,  7,  2],
       [37, 17, 11,  7,  3],
       [37, 31, 11,  5,  2]])>